@startuml
skinparam monochrome true

[*] --> EnVivo : Se arma en un Lugar

EnVivo --> Subido : Se sube a Internet


EnVivo --> Valorado : Persona da "Me gusta" 
EnVivo --> Valorado : Persona da "Hate" 


Subido --> Valorado : Persona (viendo) da "Me gusta" 
Subido --> Valorado : Persona (viendo) da "Hate" 

Valorado --> [*] : Se aplica el cambio de aura

@enduml